version: '3.8'

services:
  app:
    image: pdf-extractext:${VERSION}
    container_name: pdf_extract_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - pdf_network

networks:
  pdf_network:
    external: true
