FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    tesseract-ocr \
    libtesseract-dev \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .
COPY README.md .

RUN uv pip install --system -e . --group dev

# Copiar TODO el proyecto, no solo app/ y tests/
COPY . .

ENV PYTHONPATH=/app
ENV MONGO_URL=mongodb://mongo:27017
ENV DB_NAME=pdf_test_db
ENV MAX_PDF_SIZE_MB=10

CMD ["pytest", "tests/", "-v"]